"""
evaluate_ragas.py
-----------------
Evaluates the RAG system using the RAGAS framework.

RAGAS uses an LLM-as-judge approach — it calls an LLM to score each
answer across 4 dimensions. This gives much richer signal than simple
source-matching evaluation.

Run:
    python -m rag_sys.evaluate_ragas
"""

import sys
import os
import pandas as pd

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from datasets import Dataset
from ragas import evaluate
from ragas.metrics import (
    faithfulness,
    answer_relevancy,
    context_precision,
    context_recall,
)
from rag_sys.hybrid.hybrid_pipeline import HybridRAGPipeline


# ── Evaluation questions with reference answers ─────────────────────── #
# reference_answer: the ground truth — what a perfect answer looks like.
# RAGAS uses this to judge context_recall and answer_relevancy.

EVAL_QUESTIONS = [
    {
        "question": "What is the self-attention mechanism in transformers?",
        "reference_answer": (
            "Self-attention computes a weighted sum of all tokens, using "
            "Query, Key and Value projections to determine attention weights."
        ),
    },
    {
        "question": "How does cosine similarity work for vector search?",
        "reference_answer": (
            "Cosine similarity measures the angle between two vectors, "
            "ranging from -1 to 1, where 1 means identical direction."
        ),
    },
    {
        "question": "What is FAISS and when should I use it over ChromaDB?",
        "reference_answer": (
            "FAISS is Facebook's similarity search library, best for datasets "
            "over 10 million vectors. ChromaDB is easier with built-in metadata "
            "filtering, better for small to mid-scale use."
        ),
    },
    {
        "question": "What is faithfulness in RAG evaluation?",
        "reference_answer": (
            "Faithfulness measures whether the generated answer is factually "
            "consistent with the retrieved context, detecting hallucination."
        ),
    },
]


def build_ragas_dataset(pipeline: HybridRAGPipeline) -> Dataset:
    """
    Runs each question through the full RAG pipeline and collects:
      - question
      - answer        (generated by LLM)
      - contexts      (retrieved chunks — list of strings)
      - ground_truth  (our reference answer)

    RAGAS expects exactly this format.
    """
    questions = []
    answers = []
    contexts = []
    ground_truths = []

    print(f"Running {len(EVAL_QUESTIONS)} questions through pipeline...\n")

    for i, item in enumerate(EVAL_QUESTIONS, 1):
        q = item["question"]
        print(f"  [{i}/{len(EVAL_QUESTIONS)}] {q[:60]}...")

        # Run full RAG pipeline
        result = pipeline.query(question=q, explain=False)

        # Extract context texts from HybridResult objects
        chunk_texts = [r.text for r in result["sources"]]

        questions.append(q)
        answers.append(result["answer"])
        contexts.append(chunk_texts)
        ground_truths.append(item["reference_answer"])

    return Dataset.from_dict(
        {
            "question": questions,
            "answer": answers,
            "contexts": contexts,
            "ground_truth": ground_truths,
        }
    )


def run_ragas_evaluation():
    print("=" * 60)
    print("RAGAS Evaluation")
    print("=" * 60)

    # Build pipeline
    pipeline = HybridRAGPipeline(
        chunk_size=300,
        chunk_overlap=60,
        chunk_strategy="paragraph",
        embedding_model="BAAI/bge-small-en-v1.5",
        bm25_fetch_k=15,
        vector_fetch_k=15,
        final_k=3,
        rrf_k=60,
    )

    # Build the dataset by running all questions
    dataset = build_ragas_dataset(pipeline)

    print("\nRunning RAGAS evaluation (this calls the LLM for each metric)...")
    print("Expected time: 2-5 minutes depending on API speed.\n")

    # RAGAS needs an LLM to judge answers — configure it to use NVIDIA
    from ragas.llms import LangchainLLMWrapper
    from ragas.embeddings import LangchainEmbeddingsWrapper
    from langchain_nvidia_ai_endpoints import ChatNVIDIA, NVIDIAEmbeddings

    nvidia_key = os.environ.get("NVIDIA_API_KEY")
    if not nvidia_key:
        raise EnvironmentError("NVIDIA_API_KEY not set")

    judge_llm = LangchainLLMWrapper(
        ChatNVIDIA(
            model="meta/llama-3.1-8b-instruct",
            api_key=nvidia_key,
            max_tokens=512,
            temperature=0,
        )
    )

    judge_embeddings = LangchainEmbeddingsWrapper(
        NVIDIAEmbeddings(
            model="nvidia/nv-embedqa-e5-v5",
            api_key=nvidia_key,
        )
    )

    all_scores = {}

    for metric in [faithfulness, answer_relevancy, context_precision, context_recall]:
        metric_name = metric.name
        print(f"  Evaluating {metric_name}...")
        try:
            result = evaluate(
                dataset=dataset,
                metrics=[metric],
                llm=judge_llm,
                embeddings=judge_embeddings,
            )
            score = result.to_pandas()[metric_name].mean()
            all_scores[metric_name] = score
            print(f"    {metric_name}: {score:.3f}")
        except Exception as e:
            print(f"    {metric_name}: FAILED — {e}")
            all_scores[metric_name] = float("nan")

    # Run evaluation
    results = evaluate(
        dataset=dataset,
        metrics=[
            faithfulness,
            answer_relevancy,
            context_precision,
            context_recall,
        ],
        llm=judge_llm,
        embeddings=judge_embeddings,
    )

    print("\n" + "=" * 60)
    print("RAGAS RESULTS")
    print("=" * 60)
    print("\nAggregate scores (0-1, higher is better):\n")

    import math

    for metric_name, score in all_scores.items():
        if math.isnan(score):
            print(f"  {metric_name:22s}: N/A (timed out)")
            continue
        bar = "█" * int(score * 20) + "░" * (20 - int(score * 20))
        print(f"  {metric_name:22s}: {bar} {score:.3f}")

    print("\n" + "=" * 60)
    print("SCORE INTERPRETATION")
    print("=" * 60)
    for metric_name, score in all_scores.items():
        if math.isnan(score):
            print(f"  {metric_name:22s}: N/A")
            continue
        if score >= 0.85:
            status = "Excellent"
        elif score >= 0.70:
            status = "Good"
        elif score >= 0.55:
            status = "Needs improvement"
        else:
            status = "Poor — investigate"
        print(f"  {metric_name:22s}: {score:.3f}  {status}")

    # Save what we have
    pd.DataFrame([all_scores]).to_csv("ragas_results.csv", index=False)
    print("\nResults saved to: ragas_results.csv")
    print("=" * 60)


if __name__ == "__main__":
    from dotenv import load_dotenv

    load_dotenv()
    run_ragas_evaluation()
